idf_component_register(SRCS "usb_serial_echo_main.c"
                       "lapi.c"
                       "lauxlib.c"
                       "lcode.c"
                       "ldebug.c"
                       "ldo.c"
                       "lfunc.c"
                       "lgc.c"
                       "llex.c"
                       "lmem.c"
                       "lobject.c"
                       "lopcodes.c"
                       "lparser.c"
                       "lstate.c"
                       "lstring.c"
                       "ltable.c"
                       "ltm.c"
                       "lua_ino.c"
                       "lvm.c"
                       "lzio.c"
                       INCLUDE_DIRS ".")
